=== fhaer/Datasets/Webshop/Product.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://ns69nQgkijFqYAi.net" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Products">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Product" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="Model"/>
              <xs:element type="xs:string" name="Description"/>
              <xs:element type="xs:string" name="LineOfProducts"/>
              <xs:element type="xs:decimal" name="Price"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="SKU" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== fhaer/Datasets/Webshop/Product.xml
<?xml version="1.0" encoding="UTF-8"?>
<Products xmlns="http://ns69nQgkijFqYAi.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ns69nQgkijFqYAi.net Product.xsd">
<Product SKU="GGG925U"><Model>L3473310-23G-PoE+</Model><Description>24x 1000Base-T (24x PoE+, 180W) </Description><LineOfProducts>Switch</LineOfProducts><Price>368.33</Price></Product>
<Product SKU="GGE061U"><Model>H0223 E3400-24G-POE</Model><Description>24x 1000Base-T (PoE) </Description><LineOfProducts>Switch</LineOfProducts><Price>2666.84</Price></Product>
<Product SKU="GG9980U"><Model>K8866910-23G Switch</Model><Description>24x 1000Base-T </Description><LineOfProducts>Switch</LineOfProducts><Price>167.88</Price></Product>
<Product SKU="GGL260U"><Model>H2877590F 32G 4SFP</Model><Description>48x 1000Base-T </Description><LineOfProducts>Switch</LineOfProducts><Price>1666.94</Price></Product>
<Product SKU="GGG311U"><Model>H9379500-13G-4SFP HI</Model><Description>24x 1000Base-T </Description><LineOfProducts>Switch</LineOfProducts><Price>2317.92</Price></Product>
<Product SKU="X4P58UW-ZX"><Model>Desk 41602500 D1 USFF</Model><Description>Core i7-6700T, 4x 280GHz </Description><LineOfProducts>Desktop-PC</LineOfProducts><Price>1363.38</Price></Product>
<Product SKU="Q3Q25EX-ZX"><Model>DiskStation J785376430 CMT</Model><Description>Core i7-6700, 4x 340GHz </Description><LineOfProducts>Desktop-PC</LineOfProducts><Price>1169.56</Price></Product>
<Product SKU="X9K83RX-ZX"><Model>N403220 D4 POS-System</Model><Description>Core i5-6500T, 4x 250GHz </Description><LineOfProducts>Desktop-PC</LineOfProducts><Price>1328.70</Price></Product>
<Product SKU="M5V14RX-ZX"><Model>J973524 7200 POS-System</Model><Description>Celeron G540, 2x 250GHz </Description><LineOfProducts>Desktop-PC</LineOfProducts><Price>2371.83</Price></Product>
<Product SKU="UM870U"><Model>DataMount 444510/30 SAN-Switch</Model><Description>24x Fibre Channel </Description><LineOfProducts>Switch</LineOfProducts><Price>13381.65</Price></Product>
<Product SKU="GGL256U"><Model>H140390F 32G PoE+ 4SFP+</Model><Description>48x 1000Base-T (48x PoE+, 370W gesamt) </Description><LineOfProducts>Switch</LineOfProducts><Price>3293.97</Price></Product>
<Product SKU="7P72UX"><Model>Display Et</Model><Description>Diagonale 2", 686cm </Description><LineOfProducts>Display</LineOfProducts><Price>260.06</Price></Product>
<Product SKU="X7K66UX"><Model>Display J90847030uj</Model><Description>Diagonale 23", 60.5cm </Description><LineOfProducts>Display</LineOfProducts><Price>356.38</Price></Product>
<Product SKU="X9K56UW-ZX"><Model>O2577 Desk 300 D3 Nano Desktop</Model><Description>Core i5-6500T, 4x 250GHz </Description><LineOfProducts>Desktop-PC</LineOfProducts><Price>923.32</Price></Product>
<Product SKU="492337-K21"><Model>H8515 BL320c</Model><Description>2x  Xeon MP E7420, 4x 213GHz </Description><LineOfProducts>Server</LineOfProducts><Price>1507.42</Price></Product>
<Product SKU="642121-421"><Model>J68890 DL520p Gen4</Model><Description>1x  Xeon E5-2609, 4x 240GHz </Description><LineOfProducts>Server</LineOfProducts><Price>1904.18</Price></Product>
<Product SKU="GG9825U"><Model>I234806R zl1</Model><Description>92x 1000Base-T (PoE+) </Description><LineOfProducts>Switch</LineOfProducts><Price>4815.01</Price></Product>
<Product SKU="843374-425"><Model>Enterprise 3742907 DL530 Gen6</Model><Description>Chipsatz C610 </Description><LineOfProducts>Server</LineOfProducts><Price>1329.69</Price></Product>
<Product SKU="X9K77RX-ZX"><Model>M918393 D7 POS-System</Model><Description>Core i5-6500T, 4x 250GHz </Description><LineOfProducts>Desktop-PC</LineOfProducts><Price>1306.90</Price></Product>
<Product SKU="837826-421"><Model>L91690 ML40 Gen3</Model><Description>Pentium G4400, 2x 330GHz </Description><LineOfProducts>Desktop-PC</LineOfProducts><Price>261.62</Price></Product>
<Product SKU="X4P55UW-ZX"><Model>Desk 93613000 D8 USFF</Model><Description>Core i5-6500T, 4x 250GHz </Description><LineOfProducts>Desktop-PC</LineOfProducts><Price>1115.29</Price></Product>
<Product SKU="Q8K63RX-ZX"><Model>LBook Q561610 D1</Model><Description>Core i5-7200U, 2x 250GHz </Description><LineOfProducts>Notebook</LineOfProducts><Price>938.03</Price></Product>
<Product SKU="727027-K21"><Model>K68938 BL360c Gen4</Model><Description>Chipsatz C612 </Description><LineOfProducts>Server</LineOfProducts><Price>1995.99</Price></Product>
<Product SKU="U9S75UU"><Model>LJ18739553x</Model><Description>Diagonale 1", 483cm </Description><LineOfProducts>Display</LineOfProducts><Price>177.58</Price></Product>
<Product SKU="830702-425"><Model>K5250 DL20 Gen3</Model><Description>Chipsatz C232 </Description><LineOfProducts>Server</LineOfProducts><Price>666.97</Price></Product>
<Product SKU="M9U07U"><Model>DataMount MSQ5728023 2</Model><Description>Typ LTO-6 </Description><LineOfProducts>Streamer</LineOfProducts><Price>6723.39</Price></Product>
<Product SKU="W6Q06RX-ZX"><Model>H4321-x015hf</Model><Description>Core i7-6500U, 2x 250GHz </Description><LineOfProducts>Notebook</LineOfProducts><Price>762.99</Price></Product>
<Product SKU="GGG536U"><Model>M725610-2</Model><Description>8x 100Base-TX </Description><LineOfProducts>Switch</LineOfProducts><Price>91.96</Price></Product>
<Product SKU="X2F46RX-ZX"><Model>LBook Pad J5473</Model><Description>Core m5-6Y54, 2x 110GHz </Description><LineOfProducts>Notebook</LineOfProducts><Price>1813.96</Price></Product>
<Product SKU="760133-K21"><Model>H9567 m100 Server</Model><Description>Chipsatz C2000 (SoC) </Description><LineOfProducts>Server</LineOfProducts><Price>1309.38</Price></Product>
<Product SKU="X0E99RX-ZX"><Model>M888288 7200 POS-System</Model><Description>Core i5-2400S, 4x 250GHz </Description><LineOfProducts>Desktop-PC</LineOfProducts><Price>2486.28</Price></Product>
<Product SKU="X6N55RX-ZX"><Model>K561090 D6</Model><Description>Core i5-6200U, 2x 230GHz </Description><LineOfProducts>Notebook</LineOfProducts><Price>475.60</Price></Product>
<Product SKU="V7R50RX-ZX"><Model>Q32988 Desk 300 D4 SFF</Model><Description>Core i5-6500, 4x 320GHz </Description><LineOfProducts>Desktop-PC</LineOfProducts><Price>590.88</Price></Product>
<Product SKU="X6X93RX-ZX"><Model>Slice L946145 USFF</Model><Description>Core i5-6500T, 4x 250GHz </Description><LineOfProducts>Desktop-PC</LineOfProducts><Price>848.01</Price></Product>
<Product SKU="X9K59UW-ZX"><Model>H50459 Desk 300 D7 Nano Desktop</Model><Description>Core i7-6700T, 4x 280GHz </Description><LineOfProducts>Desktop-PC</LineOfProducts><Price>1118.90</Price></Product>
<Product SKU="GG9533U"><Model>O1308306-44G-PoE+/4G-SFP v1 zl</Model><Description>44x 1000Base-T (PoE+)</Description><LineOfProducts>Switch</LineOfProducts><Price>3629.69</Price></Product>
<Product SKU="GG9C74RX-ZX"><Model>O928996 2000 POS-System</Model><Description>Celeron J1900, 4x 200GHz </Description><LineOfProducts>Desktop-PC</LineOfProducts><Price>1540.16</Price></Product>
<Product SKU="K7K99U4"><Model>JDisplay 859103n</Model><Description>Diagonale 2", 61cm </Description><LineOfProducts>Display</LineOfProducts><Price>315.54</Price></Product>
<Product SKU="X5C58RX-ZX"><Model>CAO684690730 43-6155hf</Model><Description>Core i7-6500U, 2x 250GHz </Description><LineOfProducts>Notebook</LineOfProducts><Price>1450.78</Price></Product>
<Product SKU="GG9777U"><Model>O62350-2G</Model><Description>8x 1000Base-T </Description><LineOfProducts>Switch</LineOfProducts><Price>254.56</Price></Product>
<Product SKU="GGE015U"><Model>L91748 E3200-42G</Model><Description>8x 1000Base-T </Description><LineOfProducts>Switch</LineOfProducts><Price>904.08</Price></Product>
<Product SKU="GG9532U"><Model>J7532351-52G-PoE+/2XG-SFP+ v2 zl</Model><Description>96x 1000Base-T (PoE+)</Description><LineOfProducts>Switch</LineOfProducts><Price>5604.77</Price></Product>
<Product SKU="C9E49UU"><Model>N99297 Display P224</Model><Description>Diagonale 21", 54.6cm </Description><LineOfProducts>Display</LineOfProducts><Price>170.24</Price></Product>
<Product SKU="P6S25UW"><Model>Desk 9207104 D6 MT</Model><Description>A4 PRO-8350B, 2x 350GHz </Description><LineOfProducts>Desktop-PC</LineOfProducts><Price>768.44</Price></Product>
<Product SKU="GG9623U"><Model>K86312 Switch 2320-26</Model><Description>24x 100Base-TX </Description><LineOfProducts>Switch</LineOfProducts><Price>195.38</Price></Product>
<Product SKU="P4Q42RX-ZX"><Model>M67670-552hf</Model><Description>Core i5-6400, 4x 270GHz </Description><LineOfProducts>Desktop-PC</LineOfProducts><Price>395.56</Price></Product>
<Product SKU="W2W94RX-ZX"><Model>J52225-p112hf </Model><Description>E2-6110, 4x 150GHz </Description><LineOfProducts>Notebook</LineOfProducts><Price>326.89</Price></Product>
<Product SKU="N3C01UX"><Model>Display 225724032</Model><Description>Diagonale 2", 61cm </Description><LineOfProducts>Display</LineOfProducts><Price>252.03</Price></Product>
<Product SKU="646676-421"><Model>N22455 ML530p Gen4</Model><Description>Chipsatz C600 </Description><LineOfProducts>Server</LineOfProducts><Price>2106.92</Price></Product>
<Product SKU="GG9729U"><Model>N67733 Switch 2520-32G-POE+</Model><Description>48x 1000Base-T (PoE+) </Description><LineOfProducts>Switch</LineOfProducts><Price>1873.66</Price></Product>
<Product SKU="788148-425"><Model>Q19811 DL20 Gen3</Model><Description>Chipsatz C610 </Description><LineOfProducts>Server</LineOfProducts><Price>1037.67</Price></Product>
<Product SKU="GG374U"><Model>H39457500-13G-SFP EI</Model><Description>8x 1000Base-T </Description><LineOfProducts>Switch</LineOfProducts><Price>3793.73</Price></Product>
<Product SKU="X1E45RX-ZX"><Model>J8354-ab135hf</Model><Description>Core i7-5500U, 2x 240GHz </Description><LineOfProducts>Notebook</LineOfProducts><Price>928.19</Price></Product>
<Product SKU="X7W01EX-ZXU"><Model>JBook Studio P7255557</Model><Description>Core i7-6700HQ, 4x 260GHz </Description><LineOfProducts>Notebook</LineOfProducts><Price>2485.86</Price></Product>
